version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BACKEND_PORT=8080
      - DB_PATH=/app/data/ringtonic.db
      - STORAGE_PATH=/app/storage
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/ringtonic
      - N8N_WEBHOOK_SECRET=your-secure-secret-here
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
    depends_on:
      - n8n
    networks:
      - ringtonic-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_WEBHOOK_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=UTC
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - ringtonic-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  ringtonic-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local
